version: '3'
services:
  mongo:
    image: mongo:4.2.5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  app:
    build: .
    environment:
      - WAIT_HOSTS=mongo:27017
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    ports:
      - '8080:8080'

volumes:
  mongodb_data:
